= Home Lab Networking Gear Recommendation
Jscar
Version 0.1, 2020.02.25
:sectnums:
:toc:
:toclevels: 4
:toc-title: My Content

:description: Example AsciiDoc document
:keywords: AsciiDoc
:imagesdir: ./images


== Access Point

=== Starter Basic AP

UniFi Lite Access Point

Price $89

https://store.ui.com/collections/unifi-network-access-points/products/unifi-ac-lite

Comes with PoE injector

=== Advanced AP

UniFi 6 Lite Access Point

Price $99

https://store.ui.com/collections/unifi-network-access-points/products/unifi-ap-6-lite

Features:

* 2x2 high-efficiency Wi-Fi 6
* 5 GHz band 2x2 MU-MIMO and OFDMA with radio rate of 1.2 Gbps
* 2.4 GHz band 2x2 MIMO with radio rate of 300 Mbps
* Gigabit Ethernet, powered with 802.3af PoE

Does not come with PoE injector

=== Pro AP

UniFi PRO Access point

Price $149

https://store.ui.com/collections/unifi-network-access-points/products/unifi-ac-pro

Features:

* Simultaneous Dual-Band 3x3 MIMO
* 5 GHz Band with Speeds of up to 1300 Mbps
* 2.4 GHz Band with Speeds of up to 450 Mbps
* Range up to 122 meters (400 feet)
* 802.3af PoE / 802.3at PoE+ Compatible
* (2) Gigabit Ethernet Ports

Comes with PoE injector

== Managed Switches

=== Starter Switch
USW Flex Mini

Price $30

https://store.ui.com/collections/unifi-network-routing-switching/products/usw-flex-mini

* 5-Port managed Gigabit Ethernet switch powered by 802.3af/at PoE or 5V, 1A USB-C power adapter.
* 5V, 1A USB-C power adapter included only with the single-pack of the USW-Flex-Mini.

=== Advanced Switch
UniFi Switch 8

Price $99

https://store.ui.com/collections/unifi-network-routing-switching/products/unifi-switch-8

* (8) Gigabit Ethernet Ports
* (1) PoE Passthrough Port
* Powered by 802.3af/at PoE or DC Power
* 8 Gbps Total, Non-Blocking Line Rate
* 25W AC/DC Power Adapter Included

=== Pro Switch
UniFi Switch 24

Price $225

https://store.ui.com/collections/unifi-network-routing-switching/products/usw-24

* (24) Gigabit Ethernet Ports
* (2) Gigabit SFP Ports
* 1.3" color touchscreen for status information
* 1U rackmountable (kit included)



== UniFi Network Controller

You will need to run the UniFi Network controller on a machine to manage your gear.

This can be done on any machine that is running 24/7.

Features:

* Manage your networks from a single interface.
* Enjoy intuitive configuration options, as well as robust device control and monitoring.
* Upgrade device firmware remotely.
* Easily manage network users and guests.
* Personalize the design, architecture, and privacy of guest hotspots.

=== Raspberry Pi 4
I would suggest using a raspberry pi for this purpose.

If you buy this kit from Vilros Raspberry Pi 4-2GB RAM.

You will get the passively cooled heat-sync case that will keep your pi cool and noiseless,

with the added benefit of getting all the parts you need to get started with a pi.

https://amzn.to/3GP4qoJ - The link is Amazon Affiliate link, which helps me fund the projects I work on.


If you aleady have a Raspberry Pi this is the case I recommend.
Vilros Raspberry Pi 4 Heavy Duty Aluminum Alloy Pi Cooling Case (Black)

https://amzn.to/40fuHDl - The link is Amazon Affiliate link, which helps me fund the projects I work on.

=== Software Installed on another machine

In this page you can find the installer to run it on

* MacOS
* Windows
* Debian/Ubuntu Linux

https://www.ui.com/download/unifi/

== Firewall/Router

=== Protectli Vault 4 Port

Price $272

https://amzn.to/43EkHGG - The link is Amazon Affiliate link, which helps me fund the projects I work on.

Features:

* CPU: Intel Quad Core Celeron J3160, 64 bit, up to 2.2GHz, AES-NI hardware support
* PORTS: 4x Intel i210 Gigabit Ethernet ports, 2x USB 3.0, 1x RJ-45 COM, 2x HDMI
* COMPONENTS: 4GB DDR3L RAM, 32GB mSATA SSD. coreboot BIOS optional, must be installed by user.
* COMPATIBILITY: No OS pre-installed. All hardware tested with pfSense, untangle, OPNsense and other popular open-source software solutions.

=== Uninterruptible Power Supply - Protectli Vault

This is optional, but Highly recommended

44 Watt Hour Uninterruptible Power Supply - Protectli Vault

https://amzn.to/3UISs5G - The link is Amazon Affiliate link, which helps me fund the projects I work on.

Price $60

Features:

* Fully compatible with all Protectli Vault
* 44 Watt Hour DC-DC UPS
* Desktop or Wall Mounting
* Small, compact form factor
* DC-DC cable included
