= Podcasting/AV Gear Recommendation
Jscar
Version 0.1, 2020.03.17
:sectnums:
:toc:
:toclevels: 4
:toc-title: My Content

:description: Example AsciiDoc document
:keywords: AsciiDoc
:imagesdir: ./images

My Linux Audio and Video Setup

With a large amount the workforce going remote, I wanted to share what I am using.

To help fund the projects I work on, the links are Amazon Affiliate links. This will let amazon know I sent you, and give me a small kickback if you buy that product. None of these are sponsorship, they do not get to see what I am saying about the products before I post online. Theses are products that I use and recommend!

== Laptop 

=== Work 
Lenovo P1 Gen3

=== Personal
Framework Laptop

== Operating System
P1 Gen3 is running RHEL 9

Framework Laptop is running https://getfedora.org/en/workstation/[Fedora 36 Workstation]

== Broadcasting Software
https://obsproject.com/[Open Broadcast Studio]


== Microphones

=== Basic

https://amzn.to/3mGgXnK[Razer Seiren Mini]

=== Starter Mic

https://amzn.to/3H0gVxE[Samson Q2U USB/XLR Dynamic Microphone Recording]



=== New Mic

https://amzn.to/3HmjbQj[Rode PodMic]

== USB audio interface:

=== Beginner

https://amzn.to/41rmZHO[BEHRINGER UM2 Audio Interface]


=== Intermediate

https://amzn.to/3USV6WH[Audient EVO 4]

Works out of the Box With Fedora 35 and later,
This does not work out of the box on Fedora 33, but there is a site that can help you get up and running with it.

https://writepermission.com/evo4-pulseaudio-profile.html



== Headset:

=== Wired

https://drop.com/buy/massdrop-x-sennheiser-hd-58x-jubilee-headphones[SENNHEISER HD 58X JUBILEE HEADPHONES]

https://amzn.to/3KJUqOw[KZ ZSN Pro X in Ear Buds Earphones]

=== Wireless

https://amzn.to/3AhkWKx[Shokz OpenRun (AfterShokz Aeropex)]

== Mic Stand:

=== Starter

https://amzn.to/43KXcvR[InnoGear Heavy Duty Microphone Stand with Mic Microphone Windscreen]

=== Better

https://amzn.to/43KXcvR[Neewer Upgraded Large Sturdier Microphone Stand]



== Webcam and DSLR:

After 5 years of using this camera it died
https://amzn.to/43KXcvR[Logitech HD Pro Webcam C920]

I am currently testing the Facecam and it works with a lot of software but not everything on linux.
https://amzn.to/43KXcvR[Elgato Facecam]


https://amzn.to/3USKl6K[Sony A6000]

If you go with another camera, you will need to check for clean HDMI out.
A great sight to check for that is https://www.elgato.com/en/cam-link/camera-check.

With the Sony A6000 being unavable for the last year and a half, 
and I don't want to spend $2000 on the A7 or FX3,
I found another camera that is just as good.


I am now using a 
https://amzn.to/3KOjFQ1[Nikon Z30]
It does overheat after 2 hours of continues use, verses the Sony a6*00 Cameras.


=== SmallRig Gear

https://amzn.to/3GYflfZ[SmallRig Cage for Nikon Z 30 3858]

https://amzn.to/40oRahp[SMALLRIG Camera Cage only for Sony A6000]

https://amzn.to/41fJoaZ[SMALLRIG HDMI Cable Clamp]



=== Tripod and Mounting Gear
https://amzn.to/41fJoaZ[Moman Tripod Fluid Drag Pan Head]

https://amzn.to/41fJoaZ[KingJoy 66'' Camera Tripod]

https://amzn.to/40rtitD[Dazzne Desk Mount Stand]

https://amzn.to/3oyibla[CAMVATE Heavy-Duty C Clamp Articulated 1/4"-20 Ball Head Support Holder (Black Locking Knob)]

== Here is my sit/stand desk
https://www.homedepot.com/p/Husky-62-in-Adjustable-Height-Work-Table-HOLT62XDB12/301810799[Husky 62 in. Adjustable Height Work Table]

== Office Chair 
https://amzn.to/43LW0s4[SIHOO Office Chair with Pattern Mesh]

== Video capture card
Video capture card I use types that work with linux.

If you are looking to use a DSLR Camera,
you will have to make sure it supports Clean HDMI.
Here is a great site to check for that https://www.elgato.com/en/cam-link/camera-check[elgato clean hdmi check]

=== With Pass-through HDMI

https://amzn.to/3KQwtFq[Plugable Performance NIX Capture Card]

=== Without pass-through HDMI

https://amzn.to/43PRZCK[Mirabox Capture Card]

https://amzn.to/3LhLD8k[Mirabox USB3.0 4K HDMI Video Capture Card]

Currently Testing this card out because it treats the HDMI as UVC which acks as a camera.
So Video Calling, Camera, Mac & Linux all work out of the box.
https://amzn.to/3mLMYL3[EVGA XR1 lite Capture Card]


== Lighting Setup

=== On Camera Shoe

==== Starter

https://amzn.to/3ouXVRK[VILTROX L116T RA CRI95 Super Slim LED Light Panel]

https://amzn.to/3LeuY5f[VILTROX 2m/6.5ft Premium External Power Supply 12V 2A Output AC/DC Adapter 100-240V Input for LED Light,L116T/L116B/L13T/L132B,VILTROX Monitor DC-70/DC-50, CE FC Certification]
There are difference power supplies, but DO NOT USE THEM IF THEY ARE NOT 12V at 2A!
You will cook your light, and once the magic smoke is out, it can't be put back in.

==== Better

https://amzn.to/3H0FjiS[Elgato Key Light Air]

=== Back Lighting

==== Starter

https://amzn.to/3USG96N[Philips Color LED Wi-Fi Wiz Connected Wireless Light Bulb]

==== Better

https://amzn.to/41J8dMh[Elgato Light Strip RGBWW LEDs]


== Monitor

https://amzn.to/3LevdNH[Samsung 34-Inch SJ55W Ultrawide Gaming Monitor]

== Monitor Arm

https://amzn.to/41Kyl9M[HUANUO Single Arm Monitor Stand]
